### ISSUE TITLE
Orchestrator is not pre-set with knowledge of the cluster

### ISSUE THREAD

**Issue by jimklimov** [garutilorenzo/mysql-ha-docker#4]
Ideally, upon first boot and after a bit of time it would run a CLI command to honestly "discover" the nearby cluster. Currently this has to be clicked up in the Web-UI.

**Comment by garutilorenzo** [comment]
Fixed in b50388dd3cf1760ff35c71956fdaed413697dddd and 7a46da9b623a7489e33284f8edd4a938c9fe8064

**Comment by jimklimov** [comment]
Nice! Thanks a lot for the quick reaction here and in other issues/PRs ;)
